protected/models/Classificacao.php
<?php

Yii::import('application.models._base.BaseClassificacao');

class Classificacao extends BaseClassificacao
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
}

protected/controllers/ClasseController.php
<?php

class ClasseController extends GxController {

    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Classe'),
        ));
    }

    public function actionCreate() {
        $model = new Classe;

        if (isset($_POST['Classe'])) {
            $model->setAttributes($_POST['Classe']);

            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionUpdate($id) {
        $model = $this->loadModel($id, 'Classe');

        if (isset($_POST['Classe'])) {
            $model->setAttributes($_POST['Classe']);
            
            if ($model->save()) {
                if (isset($model->classificacoes) && !empty($model->classificacoes)) {
                    foreach ($model->classificacoes as $nclass) {
                        $codigo = strstr($nclass->codigo, '-');
                        $nclass->codigo = $model->codigo . $codigo;
                        $nclass->save();
                    }
                }

                $this->redirect(array('index'));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete($id) {
        
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $model = $this->loadModel($id, 'Classe');
            
            if (isset($model->classificacoes) && !empty($model->classificacoes))
                throw new CHttpException(400, Yii::t('app', 'Erro ao deletar. Classe pertence a um Nível de Classificação.'));
            else if ($model->ativo == 1)
                throw new CHttpException(400, Yii::t('app', 'Erro ao deletar. Classe deve estar inativa.'));
            else
                $model->delete();
            
            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('index'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    public function actionDeactivate($id) {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $model = $this->loadModel($id, 'Classe');
            $model->ativo = 0;
            $model->save();

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('index'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    public function actionActivate($id) {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $model = $this->loadModel($id, 'Classe');
            $model->ativo = 1;
            $model->save();

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('index'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    public function actionIndex() {
        $model = new Classe('search');
        $model->unsetAttributes();

        if (isset($_GET['Classe']))
            $model->setAttributes($_GET['Classe']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }

}

protected/controllers/ClassificacaoController.php
<?php

class ClassificacaoController extends GxController {

    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Classificacao'),
        ));
    }

    public function actionCreate() {
        $model = new Classificacao;
        
        if (isset($_POST['Classificacao'])) {
            $model->setAttributes($_POST['Classificacao']);
            
            if (!isset($_POST['Classificacao']['classe']) || $_POST['Classificacao']['classe'] == '')
                $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/index/error/noclass');
            
            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
            } else {
                $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/index/error/unique');
            }
        } else {
            $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/index/error/noclass');
        }

        $this->redirect(Yii::app()->request->getBaseUrl(true));
    }

    public function actionUpdate($id) {
        $model = $this->loadModel($id, 'Classificacao');


        if (isset($_POST['Classificacao'])) {
            $model->setAttributes($_POST['Classificacao']);

            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete($id) {
        $model = Classificacao::model()->findByPk($id);
        $error = '';
        
        if ($model) {
            if (isset($model->itensDocumentais) && !empty($model->itensDocumentais)) {
                $error = 'Erro ao deletar Nível de Classificação "' . $model->codigo . '".';
            } else {
                $model->delete();
                $error = 'success';
            }
        }
        echo $error;
    }

    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Classificacao');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionAdmin() {
        $model = new Classificacao('search');
        $model->unsetAttributes();

        if (isset($_GET['Classificacao']))
            $model->setAttributes($_GET['Classificacao']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }
    
}

protected/controllers/GrupoController.php
<?php

class GrupoController extends GxController {

    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Grupo'),
        ));
    }

    public function actionCreate() {
        $model = new Grupo;


        if (isset($_POST['Grupo'])) {
            $model->setAttributes($_POST['Grupo']);
            $model->data = date("Y-m-d H:i:s");
            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionDelete($id) {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $model = $this->loadModel($id, 'Grupo');
            
            if (isset($model->classificacoes) && !empty($model->classificacoes)) {
                throw new CHttpException(400, Yii::t('app', 'Erro ao deletar. Grupo pertence a um Nível de Classificação.'));
            } else {
                $model->delete();
            }

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }
/*
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Grupo');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }
 * 
 */

    public function actionIndex() {
        $model = new Grupo('search');
        $model->unsetAttributes();

        if (isset($_GET['Grupo']))
            $model->setAttributes($_GET['Grupo']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }

}

protected/controllers/SubclasseController.php
<?php

class SubclasseController extends GxController {

    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Subclasse'),
        ));
    }

    public function actionCreate() {
        $model = new Subclasse;


        if (isset($_POST['Subclasse'])) {
            $model->setAttributes($_POST['Subclasse']);

            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionDelete($id) {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $model = $this->loadModel($id, 'Subclasse');

            if (isset($model->classificacoes) && !empty($model->classificacoes)) {
                throw new CHttpException(400, Yii::t('app', 'Erro ao deletar. Subclasse pertence a um Nível de Classificação.'));
            } else {
                $model->delete();
            }

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    /*
      public function actionIndex() {
      $dataProvider = new CActiveDataProvider('Subclasse');
      $this->render('index', array(
      'dataProvider' => $dataProvider,
      ));
      }
     */

    public function actionIndex() {
        $model = new Subclasse('search');
        $model->unsetAttributes();

        if (isset($_GET['Subclasse']))
            $model->setAttributes($_GET['Subclasse']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }

}

protected/controllers/SubgrupoController.php
<?php

class SubgrupoController extends GxController {

    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Subgrupo'),
        ));
    }

    public function actionCreate() {
        $model = new Subgrupo;


        if (isset($_POST['Subgrupo'])) {
            $model->setAttributes($_POST['Subgrupo']);

            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionDelete($id) {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $model = $this->loadModel($id, 'Subgrupo');

            if (isset($model->classificacoes) && !empty($model->classificacoes)) {
                throw new CHttpException(400, Yii::t('app', 'Erro ao deletar. Subgrupo pertence a um Nível de Classificação.'));
            } else {
                $model->delete();
            }

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    /*
      public function actionIndex() {
      $dataProvider = new CActiveDataProvider('Subgrupo');
      $this->render('index', array(
      'dataProvider' => $dataProvider,
      ));
      }
     */

    public function actionIndex() {
        $model = new Subgrupo('search');
        $model->unsetAttributes();

        if (isset($_GET['Subgrupo']))
            $model->setAttributes($_GET['Subgrupo']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }

}

protected/views/classificacao/_form.php
<div class="form">

    <?php
    $form = $this->beginWidget('GxActiveForm', array(
        'id' => 'classificacao-form',
        'enableAjaxValidation' => false,
        'action' => Yii::app()->request->getBaseUrl(true) . '/classificacao/create'
    ));
    ?>

    <fieldset>
        <div class="row-inline">
            <?php echo $form->labelEx($model, 'classe'); ?>
            <?php echo $form->dropDownList($model, 'classe', GxHtml::listDataEx(Classe::model()->findAllAttributes(null, true))); ?>
            <?php echo $form->error($model, 'classe'); ?>
        </div><!-- row -->
        <div class="row-inline">
            <?php echo $form->labelEx($model, 'subclasse'); ?>
            <?php echo $form->dropDownList($model, 'subclasse', GxHtml::listDataEx(Subclasse::model()->findAllAttributes(null, true)), array('empty' => '')); ?>
            <?php echo $form->error($model, 'subclasse'); ?>
        </div><!-- row -->
        <div class="row-inline">
            <?php echo $form->labelEx($model, 'grupo'); ?>
            <?php echo $form->dropDownList($model, 'grupo', GxHtml::listDataEx(Grupo::model()->findAllAttributes(null, true)), array('empty' => '')); ?>
            <?php echo $form->error($model, 'grupo'); ?>
        </div><!-- row -->
        <div class="row-inline">
            <?php echo $form->labelEx($model, 'subgrupo'); ?>
            <?php echo $form->dropDownList($model, 'subgrupo', GxHtml::listDataEx(Subgrupo::model()->findAllAttributes(null, true)), array('empty' => '')); ?>
            <?php echo $form->error($model, 'subgrupo'); ?>
        </div><!-- row -->
        <div class="row-inline">
            <?php echo $form->labelEx($model, 'unidade_arquivamento'); ?>
            <?php echo $form->dropDownList($model, 'unidade_arquivamento', GxHtml::listDataEx(UnidadeArquivamento::model()->findAllAttributes(null, true)), array('empty' => '')); ?>
            <?php echo $form->error($model, 'unidade_arquivamento'); ?>
        </div><!-- row -->

        <?php
        echo GxHtml::submitButton(Yii::t('app', 'Save'));
        $this->endWidget();
        ?>

        <?php if (isset($error) && $error != '') { ?>
            <div class="error" style="display: inline-block; color: red; margin-left: 10px;">
                <?php
                switch ($error) {
                    case 'unique':
                        echo 'Nível de Classificação já existe.';
                        break;
                    case 'noclass':
                        echo 'Classe é obrigatório.';
                        break;
                    default:
                        break;
                }
                ?>
            </div>
        <?php } ?>

    </fieldset>
</div><!-- form -->

protected/views/classificacao/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'id'); ?>
		<?php echo $form->textField($model, 'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'codigo'); ?>
		<?php echo $form->textField($model, 'codigo', array('maxlength' => 29)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'classe'); ?>
		<?php echo $form->dropDownList($model, 'classe', GxHtml::listDataEx(Classe::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'subclasse'); ?>
		<?php echo $form->dropDownList($model, 'subclasse', GxHtml::listDataEx(Subclasse::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'grupo'); ?>
		<?php echo $form->dropDownList($model, 'grupo', GxHtml::listDataEx(Grupo::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'subgrupo'); ?>
		<?php echo $form->dropDownList($model, 'subgrupo', GxHtml::listDataEx(Subgrupo::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'unidade_arquivamento'); ?>
		<?php echo $form->dropDownList($model, 'unidade_arquivamento', GxHtml::listDataEx(UnidadeArquivamento::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Search')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/classificacao/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('codigo')); ?>:
	<?php echo GxHtml::encode($data->codigo); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('classe')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idClasse)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('subclasse')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idSubclasse)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('grupo')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idGrupo)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('subgrupo')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idSubgrupo)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('unidade_arquivamento')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idUnidadeArquivamento)); ?>
	<br />

</div>

protected/views/classificacao/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('classificacao-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'classificacao-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'id',
		'codigo',
		array(
				'name'=>'classe',
				'value'=>'GxHtml::valueEx($data->idClasse)',
				'filter'=>GxHtml::listDataEx(Classe::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'subclasse',
				'value'=>'GxHtml::valueEx($data->idSubclasse)',
				'filter'=>GxHtml::listDataEx(Subclasse::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'grupo',
				'value'=>'GxHtml::valueEx($data->idGrupo)',
				'filter'=>GxHtml::listDataEx(Grupo::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'subgrupo',
				'value'=>'GxHtml::valueEx($data->idSubgrupo)',
				'filter'=>GxHtml::listDataEx(Subgrupo::model()->findAllAttributes(null, true)),
				),
		/*
		array(
				'name'=>'unidade_arquivamento',
				'value'=>'GxHtml::valueEx($data->idUnidadeArquivamento)',
				'filter'=>GxHtml::listDataEx(UnidadeArquivamento::model()->findAllAttributes(null, true)),
				),
		*/
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

protected/views/classificacao/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/views/classificacao/index.php
<?php

$this->breadcrumbs = array(
	Classificacao::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Create') . ' ' . Classificacao::label(), 'url' => array('create')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . Classificacao::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Classificacao::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

protected/views/classificacao/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(
	array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

protected/views/classificacao/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
'codigo',
array(
			'name' => 'idClasse',
			'type' => 'raw',
			'value' => $model->idClasse !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idClasse)), array('classe/view', 'id' => GxActiveRecord::extractPkValue($model->idClasse, true))) : null,
			),
array(
			'name' => 'idSubclasse',
			'type' => 'raw',
			'value' => $model->idSubclasse !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idSubclasse)), array('subclasse/view', 'id' => GxActiveRecord::extractPkValue($model->idSubclasse, true))) : null,
			),
array(
			'name' => 'idGrupo',
			'type' => 'raw',
			'value' => $model->idGrupo !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idGrupo)), array('grupo/view', 'id' => GxActiveRecord::extractPkValue($model->idGrupo, true))) : null,
			),
array(
			'name' => 'idSubgrupo',
			'type' => 'raw',
			'value' => $model->idSubgrupo !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idSubgrupo)), array('subgrupo/view', 'id' => GxActiveRecord::extractPkValue($model->idSubgrupo, true))) : null,
			),
array(
			'name' => 'idUnidadeArquivamento',
			'type' => 'raw',
			'value' => $model->idUnidadeArquivamento !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idUnidadeArquivamento)), array('unidadeArquivamento/view', 'id' => GxActiveRecord::extractPkValue($model->idUnidadeArquivamento, true))) : null,
			),
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('itensDocumentais')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->itensDocumentais as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('itemDocumental/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>